apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: whoami
  name: whoami
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - image: ggiunta/whoami:$(TAG)
          name: whoami
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
      securityContext: {}
